### ISSUE TITLE
UnicodeDecodeError also happens on Python3

### ISSUE THREAD

**Issue by shimibo** [ponty/EasyProcess#14]
Change line #60 in *unicodeutil.py* to:
`s = s.decode('utf-8', 'ignore')`
Same as in Python2 code just below.

Example:
Python 3.6.3 (default, Oct  3 2017, 21:45:48) 
**from easyprocess import EasyProcess**
**proc = EasyProcess(['whois', '-H', 'chp.edu']).call()**
`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shimi/cyberjack/crr/venv3/lib/python3.6/site-packages/easyprocess/__init__.py", line 194, in call
    self.start().wait(timeout=timeout)
  File "/home/shimi/cyberjack/crr/venv3/lib/python3.6/site-packages/easyprocess/__init__.py", line 268, in wait
    self._wait4process()
  File "/home/shimi/cyberjack/crr/venv3/lib/python3.6/site-packages/easyprocess/__init__.py", line 317, in _wait4process
    self.stdout = remove_ending_lf(unidecode(self.stdout))
  File "/home/shimi/cyberjack/crr/venv3/lib/python3.6/site-packages/easyprocess/unicodeutil.py", line 60, in unidecode
    s = s.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 116: invalid start byte
`

**Comment by ponty** [comment]
Thanks!
